spring.application.name=payment-connector
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_connector
spring.datasource.username=payment_connector
spring.datasource.password=payment_connector

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

integrations.ecommerce.base-url=http://localhost:8090
integrations.payment-gateway.base-url=http://localhost:12111
